### ISSUE TITLE
barebone/shell的代碼中缺少對退格鍵的處理

### ISSUE THREAD

**Issue by DasCrystal** [kagurazakakotori/ubmp-cn-code#1]
在 barebone/shell 的代碼中缺少對 '\b' 的處理，
這會造成使用過BackSpace的輸入不能被正確的識別，
舉個例子，假設原本輸入了"helloa"，然後把最後面的'a'用BackSpace刪掉，
那麼指令看起來是"hello"，實則輸入了"helloa\b"。

**Comment by kagurazakakotori** [comment]
非常感谢您提出这一issue，关于您所提到的问题，已在 650fd49b3014dec1a5117f92abfb994adc43e120 中修复
